enjoy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flower.urls')),
    path('animal/', include('animal.urls')),
    path('daylife/', include('daylife.urls'))
]

flower/urls.py
from django.urls import path
from flower import views

app_name = 'flower'
urlpatterns = [
    path('',views.index),
    path('flower_detail/',views.flower_detail,name='f_detail'),
    path('flower_list/',views.flower_list,name='f_list'),
    path('flower_add/',views.flower_add,name='f_add'),
    path('list_ajax/',views.list_ajax)
]

flower/models.py
from django.db import models

# Create your models here.
class Flower(models.Model):
    name = models.CharField(max_length=32)
    introduce = models.CharField(max_length=128)
    picture = models.ImageField(upload_to='flower/images')

class FlowewrPic(models.Model):
    fpicture = models.ImageField(upload_to='flower/images')
    flower = models.ForeignKey(to='Flower',on_delete=models.CASCADE)

flower/views.py
from django.shortcuts import render
from django.http import JsonResponse,HttpResponse
from django.shortcuts import redirect
from django.core.paginator import Paginator
from flower.models import *


# Create your views here.
def index(request):
    flower_list = Flower.objects.all()
    return render(request, 'flower/index.html', locals())


def flower_detail(request):
    id = request.GET.get('id')
    flower = Flower.objects.get(id=int(id))
    name = flower.name[-2:]
    flower_list=Flower.objects.filter(name__contains=name)
    print(flower_list)
    picture_list = flower.flowewrpic_set.all()
    return render(request, 'flower/flower_detail.html', locals())


def flower_list(request):
    flower_list = Flower.objects.all()
    paginate = Paginator(flower_list, 4)
    range = list(paginate.page_range)
    print(range)
    return render(request,'flower/flower_list.html',locals())


def list_ajax(request):  #使用vue分页 创建接口
    result = {'code': 200, 'data': []}
    page = request.GET.get('page', 1)
    flower_list = Flower.objects.all()
    paginate = Paginator(flower_list, 4)
    result['page_range'] = list(paginate.page_range)
    print(result['page_range'])
    result['page'] = page
    page_data = paginate.page(int(page))
    for p_data in page_data:
        result_dict = {
            'id':p_data.id,
            'name': p_data.name,
            'introduce': p_data.introduce,
            'picture': p_data.picture.name
        }

        result['data'].append(result_dict)

    return JsonResponse(result,safe=False,json_dumps_params={'ensure_ascii':False})


def flower_add(request):
    if request.method == 'POST':
        fname = request.POST.get('fname')
        fintroduce = request.POST.get('fintroduce')
        fpicture = request.FILES.get('fpicture')
        f = Flower()
        f.name = fname
        f.introduce = fintroduce
        f.picture = fpicture
        f.save()
        return redirect('flower:f_list')
    return render(request, 'flower/flower_add.html')

templates/flower/flower_add.html
{% extends 'base.html' %}
{% block content %}

    <!--移动端  Mmenu-->
    <nav id="mmenu">
        <ul>
            <li><a href="">English</a></li>
            <li><a href="index.html">首 页</a></li>
            <li><a href="brand.html">品牌简介</a>
                <ul>
                    <li><a href="brand.html">品牌简介</a></li>
                    <li><a href="">企业文化</a></li>
                    <li><a href="honor.html">荣誉资质</a></li>
                </ul>
            </li>
            <li><a href="product.html">产品中心</a>
                <ul>
                    <li><a href="">婚礼花艺</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>
                    <li><a href="product.html">爱情鲜花</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="product.html">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>
                    <li><a href="">长辈鲜花</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>

                </ul>
            </li>
            <li><a href="case.html">经典案例</a>
                <ul>
                    <li><a href="case.html">经典案例</a></li>
                    <li><a href="">新增分类</a></li>
                </ul>
            </li>
            <li><a href="flower.html">花之物语</a>
                <ul>
                    <li><a href="flower.html">花之物语</a></li>
                    <li><a href="">养花知识</a></li>
                </ul>
            </li>
            <li><a href="contact.html">联系我们</a>
                <ul>
                    <li><a href="contact.html">联系我们</a></li>
                    <li><a href="message.html">在线留言</a></li>
                    <li><a href="job.html">人才招聘</a></li>
                </ul>
            </li>
        </ul>
    </nav>

    </div>

    <!--内页内容区域-->
    <div class="container ny-wrap">
        <div class="pro-title clearfix">
            <span class="pull-left">信息详情</span>
            <p class="pull-right">
                {#			<a href="contact.html">联系我们</a><em>|</em>#}
                {#			<a class="active" href="message.html">在线留言</a><em>|</em>#}
                {#			<a href="job.html">人才招聘</a>#}
            </p>
        </div>
        <div class="container message">
            <div class="messageh">
                <h2>There is doubt through the below <br/>message to consult us! </h2>
                <span></span>
            </div>
            <div class="message-con clearfix">
                <div class="mcon-left pic pull-left"><img src="/static/images/message.png" class="vcenter" alt=""/>
                </div>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mcon-right pull-right">
                        <label><span>花名</span><input type="text" name="fname" id="fname" value=""><em>*</em></label>
                        <label><span>花语</span><textarea name="fintroduce" id="fintroduce" placeholder="" class="mcontent"></textarea><em>*</em></label>
                        <label><span>照片</span><input type="file" name="fpicture" id="fpicture" class="madd"/><em>*</em></label>
                        <br>
                        <label><input type="submit" class="msub" value="提交"/></label>
                    </div>
                </form>
            </div>
        </div>


        <!--花之物语-->
        <div class="container flower-tips clearfix">
            <div class="flowerh pull-left">
                <h3>FLOWER TIPS</h3>
                <div><span>花之物语</span><em></em></div>
                <a href="flower.html">查看更多</a>
                <p>我们希望，通过花盒把爱情，亲情以及友情直观的表达出来，无需多言，一切尽在花盒当中。</p>
            </div>
            <div class="flowertips-con pull-right">
                <div class="flower-con">
                    <ul>
                        <li>
                            <div class="flower-ch">
                                <span>06-12</span><a href="flower_show.html">时尚广告片中的自然花艺某某鲜花测试文字</a>
                                <div class="line"></div>
                            </div>
                            <p>2016年6月6日，第十届虎啸国际高峰论坛暨第七届虎啸奖颁奖盛典在上海隆重举行。作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办... </p>
                            <a class="gengduo" href="flower_show.html">Read more</a>
                        </li>
                        <li>
                            <div class="flower-ch">
                                <span>06-12</span><a href="flower_show.html">鲜花测试文字母亲节之与妈妈的美丽“花约”</a>
                                <div class="line"></div>
                            </div>
                            <p>作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办七届。在本届颁奖盛典上，某某科技有限公司创始人·总裁赵旭隆先生荣膺“年度人物大奖” </p>
                            <a class="gengduo" href="flower_show.html">Read more</a>
                        </li>
                        <li class="last">
                            <div class="flower-ch">
                                <span>06-12</span><a href="flower_show.html">时尚广告片中的自然花艺某某鲜花测试文字</a>
                                <div class="line"></div>
                            </div>
                            <p>2016年6月6日，第十届虎啸国际高峰论坛暨第七届虎啸奖颁奖盛典在上海隆重举行。作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办... </p>
                            <a class="gengduo" href="flower_show.html">Read more</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/flower/flower_detail.html
{% extends 'base.html' %}
{% block content %}

    <!--内页内容区域-->
    <div class="container ny-wrap">
        <div class="pro-title clearfix">
            <span class="pull-left">展示中心</span>
            <p class="pull-right">
                <a href="#">花之物语</a><em>|</em>
                <a class="active" href="product.html">爱情鲜花</a><em>|</em>
                <a href="#">萌宠屋</a>
            </p>
        </div>
        <div class="container love-wrap pro-con proshow-con">

            <div class="proshow clearfix">
                <div class="prosleft pull-left">
                    <div class="products-pic-max f-l" id="slick-1">
                        <div><span class="pic"><img src="/static/{{ flower.picture }}" class="vcenter"
                                                    alt=""/><i></i></span></div>
                    </div>
                </div>
                <div class="prosright pull-right">
                    <h3>{{ flower.name }}</h3>
                    <div class="txt" id="cont1">
                        <p>{{ flower.introduce }}</p>
                    </div>
                    <div class="products-pic-min clearfix" id="slick-2">
                        {% for picture in picture_list %}
                        <div><span class="pic"><img src="/static/{{ picture.fpicture }}" class="vcenter"
                                                    alt=""/><i></i></span></div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>


        <!--相关产品-->
        <div class="container xgcp love-wrap">
            <div class="xgcp-title">
                <h3>相似品质</h3>
                <p>We hope that through the flower box of love, affection and friendship express intuitive, needless to
                    say, everything is in the middle of the flower box. </p>
            </div>
            <ul class="clearfix xgcp-con">
                {% for flower in flower_list %}
                    <div>
                    <li>
                        <div class="pic"><a href="{% url 'flower:f_detail' %}?id={{ flower.id }}"><img src="/static/{{ flower.picture }}"
                                                                           class="vcenter"/></a></div>
                        <p><a href="{% url 'flower:f_detail' %}?id={{ flower.id }}">{{ flower.name }}</a></p>
                    </li>
                </div>
                {% endfor %}
            </ul>
        </div>

        <!--花之物语-->
        <div class="container flower-tips clearfix">
            <div class="flowerh pull-left">
                <h3>FLOWER TIPS</h3>
                <div><span>花之物语</span><em></em></div>
                <a href="flower.html">查看更多</a>
                <p>我们希望，通过花盒把爱情，亲情以及友情直观的表达出来，无需多言，一切尽在花盒当中。</p>
            </div>
            <div class="flowertips-con pull-right">
                <div class="flower-con">
                    <ul>
                        <li>
                            <div class="flower-ch">
                                <span>06-12</span><a href="flower_show.html">时尚广告片中的自然花艺某某鲜花测试文字</a>
                                <div class="line"></div>
                            </div>
                            <p>2016年6月6日，第十届虎啸国际高峰论坛暨第七届虎啸奖颁奖盛典在上海隆重举行。作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办... </p>
                            <a class="gengduo" href="flower_show.html">Read more</a>
                        </li>
                        <li>
                            <div class="flower-ch">
                                <span>06-12</span><a href="flower_show.html">鲜花测试文字母亲节之与妈妈的美丽“花约”</a>
                                <div class="line"></div>
                            </div>
                            <p>作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办七届。在本届颁奖盛典上，某某科技有限公司创始人·总裁赵旭隆先生荣膺“年度人物大奖” </p>
                            <a class="gengduo" href="flower_show.html">Read more</a>
                        </li>
                        <li class="last">
                            <div class="flower-ch">
                                <span>06-12</span><a href="flower_show.html">时尚广告片中的自然花艺某某鲜花测试文字</a>
                                <div class="line"></div>
                            </div>
                            <p>2016年6月6日，第十届虎啸国际高峰论坛暨第七届虎啸奖颁奖盛典在上海隆重举行。作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办... </p>
                            <a class="gengduo" href="flower_show.html">Read more</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>


    </div>

{% endblock %}

{% block script %}
    <!--移动端导航-->
    <script src="/static/js/jquery.mmenu.all.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="/static/js/jquery.mCustomScrollbar.concat.min.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript">

        jQuery(function () {

            jQuery(window).load(function () {
                $("#cont1").mCustomScrollbar();
                $("#cont2").mCustomScrollbar({
                    horizontalScroll: true
                });
            })

        })

    </script>
    <script src="/static/js/public.js" type="text/javascript" charset="utf-8"></script>

    <!--slick-->
    <script src="/static/js/slick.min.js" type="text/javascript" charset="utf-8"></script>


    <!--placeholder-->
    <script src="/static/js/jquery.placeholder.min.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript">
        $(function () {
            $('input, textarea').placeholder();
        });
    </script>
    <script type="text/javascript">

        $("#slick-1").slick({
            fade: true,
            useTransform: true,
            arrows: false,
            asNavFor: "#slick-2"
        })
        $("#slick-2").slick({
            focusOnSelect: true,
            slidesToShow: 4,
            useTransform: true,
            arrows: true,
            asNavFor: "#slick-1"
        });
        $(".products-pic2").slick({
            arrows: false,
            dots: true,
            autoplaySpeed: 2000,
            autoplay: true,
            speed: 500,
        })
        $(".xgcp-con").slick({
            arrows: true,
            slidesToShow: 4,
            dots: false,
            autoplaySpeed: 2000,
            autoplay: true,
            speed: 500,
        })
        $(".phone-xgcp").slick({
            arrows: true,
            slidesToShow: 2,
            dots: false,
            autoplaySpeed: 2000,
            autoplay: true,
            speed: 500,
        })

    </script>
    <!--<script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->

{% endblock %}

templates/flower/flower_list.html
{% extends 'base.html' %}
{% block content %}


    <!--移动端  Mmenu-->
    <nav id="mmenu">
        <ul>
            <li><a href="">English</a></li>
            <li><a href="index.html">首 页</a></li>
            <li><a href="brand.html">品牌简介</a>
                <ul>
                    <li><a href="brand.html">品牌简介</a></li>
                    <li><a href="">企业文化</a></li>
                    <li><a href="honor.html">荣誉资质</a></li>
                </ul>
            </li>
            <li><a href="{% url 'flower:f_list' %}">产品中心</a>
                <ul>
                    <li><a href="">婚礼花艺</a>

                    </li>
                    <li><a href="{% url 'flower:f_list' %}">爱情鲜花</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="{% url 'flower:f_list' %}">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>
                    <li><a href="">长辈鲜花</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>

                </ul>
            </li>
            <li><a href="case.html">经典案例</a>
                <ul>
                    <li><a href="case.html">经典案例</a></li>
                    <li><a href="">新增分类</a></li>
                </ul>
            </li>
            <li><a href="flower.html">花之物语</a>
                <ul>
                    <li><a href="flower.html">花之物语</a></li>
                    <li><a href="">养花知识</a></li>
                </ul>
            </li>
            <li><a href="contact.html">联系我们</a>
                <ul>
                    <li><a href="contact.html">联系我们</a></li>
                    <li><a href="message.html">在线留言</a></li>
                    <li><a href="job.html">人才招聘</a></li>
                </ul>
            </li>
        </ul>
    </nav>

    </div>

    <!--内页内容区域-->
    <div class="container ny-wrap">
        <div class="pro-title clearfix">
            <span class="pull-left">产品中心</span>
            <p class="pull-right">
                <a href="{% url 'flower:f_add' %}">欢迎补充</a>
            </p>
        </div>
        <div class="container love-wrap pro-con">

            <div class="fenlei">
                <a href="#">求婚必备</a>
                <a class="active" href="#">情人节专属</a>
                <a href="#">其他鲜花</a>
            </div>
            {% verbatim myblock %}
                <div id="content">
                    <ul class="clearfix">
                        <li v-for="flower in page_data">
                            <div class="pic"><a v-bind:href="'/flower_detail/?id='+flower.id">
                                <img :src="'/static/'+flower.picture" class="vcenter"/></a></div>
                            <p><a v-bind:href="'/flower_detail/?id='+flower.id">{{ flower.name }}</a></p>
                        </li>
                    </ul>
                    <div class="dataTables_paginate paging_simple_numbers">
                        <ul class="pagination">
                            <li v-for="p in page_range " class="paginate_button page-item previous">
                                <a v-on:click="get_page(p)" class="page-link">{{ p }}</a>
                            </li>
                        </ul>
                    </div>
                </div>
            {% endverbatim myblock %}
        </div>
    </div>

{% endblock %}

{% block script %}
    <script>
        Vue.use(VueResource);
        var vue = new Vue(
            {
                el: '#content',//控制范围
                data: {
                    page_data: [],
                    page_range: [],
                    page: 1,

                },
                created: function () {
                    this.$http.get('/list_ajax/').then(
                        function (data) {
                            this.page_data = data['body']['data'];
                            this.page = data['body']['page'];
                            this.page_range = data['body']['page_range'];
                            console.log(data)
                        },
                        function (error) {
                            console.log(error)
                        }
                    )
                },
                methods: {
                    get_page: function (page) {
                        console.log(page);
                        var url = '/list_ajax/?page=' + page;
                        this.$http.get(url).then(
                            function (data) {
                                this.page_data = data['body']['data'];
                                this.page = data['body']['page'];
                                this.page_range = data['body']['page_range'];
                                console.log(data)
                            },
                            function (error) {
                                console.log(error)
                            }
                        )
                    }
                }
            }
        )

    </script>
{% endblock %}

templates/flower/index.html
{% extends 'base.html' %}
{% load OurTag %}
{% block content %}

    <!--移动端  Mmenu-->
    <nav id="mmenu">
        <ul>
            <li><a href="">English</a></li>
            <li><a href="/">首 页</a></li>
            <li><a href="brand.html">品牌简介</a>
                <ul>
                    <li><a href="brand.html">品牌简介</a></li>
                    <li><a href="">企业文化</a></li>
                    <li><a href="honor.html">荣誉资质</a></li>
                </ul>
            </li>
            <li><a href="{% url 'flower:f_list' %}">产品中心</a>
                <ul>
                    <li><a href="">婚礼花艺</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'flower:f_list' %}">爱情鲜花</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="{% url 'flower:f_list' %}">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>
                    <li><a href="">长辈鲜花</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>

                </ul>
            </li>
            <li><a href="case.html">经典案例</a>
                <ul>
                    <li><a href="case.html">经典案例</a></li>
                    <li><a href="">新增分类</a></li>
                </ul>
            </li>
            <li><a href="flower.html">花之物语</a>
                <ul>
                    <li><a href="flower.html">花之物语</a></li>
                    <li><a href="">养花知识</a></li>
                </ul>
            </li>
            <li><a href="contact.html">联系我们</a>
                <ul>
                    <li><a href="contact.html">联系我们</a></li>
                    <li><a href="message.html">在线留言</a></li>
                    <li><a href="job.html">人才招聘</a></li>
                </ul>
            </li>
        </ul>
    </nav>



    <!--爱情鲜花-->
    <div class="container love-flowers clearfix">
        <div class="loveh">
            花之物语<span>Love flowers</span><a href="{% url 'flower:f_list' %}" class="detai pull-right">+</a>
            <div class="line-bottom"></div>
        </div>
        <div class="love-wrap">

            <ul class="clearfix">
                {% for flower in flower_list|limit_4 %}
                    <li class="wow bounceIn" data-wow-delay="0.4s">
                        <div class="pic"><a href="{% url 'flower:f_detail' %}?id={{ flower.id }}"><img src="/static/{{ flower.picture }}"
                                                                                    class="vcenter"/></a></div>
                        <p><a href="{% url 'flower:f_detail' %}?id={{ flower.id }}">{{ flower.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>


    <div class="brand-in container">
        <div class="brand-in-wrap">
            <div class="brand-left wow fadeInLeft" data-wow-delay="0.4s">
                <div class="loveh">
                    2020<span>Brand introduction </span>
                    <div class="line-bottom"></div>
                </div>
                <p>2019年即将结束，往后的日子都是崭新的，连呼吸的空气也是新的，那就怀着满腔热情，一切重新出发吧! <br>
                    2020，我们都要好好的，把烦恼抛在一边，把快乐记在心间，看不惯的事，躲远点，熬不过的难，别抱怨。<br>
                    世事苍茫，岁月无常，愿你别回头也别将就，享受每时刻，都是最好的安排，2019再见，2020你好!
                </p>
                <em>愿 2020岁岁常欢愉，万事皆胜意</em>
                <div class="read-more">
                    <a href="brand.html">Read more</a>
                </div>
            </div>
            <div class="brand-right wow fadeInRight" data-wow-delay="0.4s">
                <img src="/static/images/brand-in.png" alt=""/>
            </div>
        </div>
    </div>
    <!--经典案例-->

    <div class="sycase container">
        <div class="sycase-wrap clearfix">
            <div class="sycase-title">
                <div class="sycase-txt">经典案例</div>
            </div>
            <ul>
                <li class="wow fadeInDown" data-wow-delay="0.4s">
                    <div class="pic"><a href="case_show.html"><img src="/static/images/sycase5.jpg" class="vcenter"
                                                                   alt=""/></a></div>
                    <a href="case_show.html" class="case-zzc">
                        <h3>婚礼花艺</h3>
                        <p>某某鲜花礼品网，中国鲜花行业品牌服务商（2013、2015两次获得行业殊荣：中国电子商务协会评定为“中国互联网电子商务鲜花礼品行业龙头企业”），隶属于....</p>
                    </a>
                </li>
                <li class="wow fadeInDown" data-wow-delay="0.4s">
                    <div class="pic"><a href="case_show.html"><img src="/static/images/sycase6.jpg" class="vcenter"
                                                                   alt=""/></a></div>
                    <a href="case_show.html" class="case-zzc">
                        <h3>婚礼花艺</h3>
                        <p>某某鲜花礼品网，中国鲜花行业品牌服务商（2013、2015两次获得行业殊荣：中国电子商务协会评定为“中国互联网电子商务鲜花礼品行业龙头企业”），隶属于....</p>
                    </a>
                </li>
                <li class="wow fadeInUp" data-wow-delay="0.4s">
                    <div class="pic"><a href="case_show.html"><img src="/static/images/sycase7.jpg" class="vcenter"
                                                                   alt=""/></a></div>
                    <a href="case_show.html" class="case-zzc">
                        <h3>婚礼花艺</h3>
                        <p>某某鲜花礼品网，中国鲜花行业品牌服务商（2013、2015两次获得行业殊荣：中国电子商务协会评定为“中国互联网电子商务鲜花礼品行业龙头企业”），隶属于....</p>
                    </a>
                </li>
                <li class="wow fadeInUp" data-wow-delay="0.4s">
                    <div class="pic"><a href="case_show.html"><img src="/static/images/sycase8.jpg" class="vcenter"
                                                                   alt=""/></a></div>
                    <a href="case_show.html" class="case-zzc">
                        <h3>婚礼花艺</h3>
                        <p>某某鲜花礼品网，中国鲜花行业品牌服务商（2013、2015两次获得行业殊荣：中国电子商务协会评定为“中国互联网电子商务鲜花礼品行业龙头企业”），隶属于....</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <!--萌宠宝贝-->
   {% include 'animal/animals_include.html' %}

{% endblock %}