animal/urls.py
from django.urls import path,re_path
from animal import views

app_name = 'animal'
urlpatterns = [
    path('index/',views.index,name='a_index'),
    path('list/',views.list,name = 'a_list'),
    path('add/',views.add,name = 'a_add'),

]

enjoy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flower.urls')),
    path('animal/', include('animal.urls')),
    path('daylife/', include('daylife.urls'))
]

animal/models.py
from django.db import models

# Create your models here.
class Animal(models.Model):
    name = models.CharField(max_length=32)
    title = models.CharField(max_length=64)
    descript = models.CharField(max_length=64)

class AnimalStore(models.Model):
    title = models.CharField(max_length=32)
    loge = models.ImageField(upload_to='animal/images')
    store = models.TextField()
    origin = models.CharField(max_length=32)
    data = models.CharField(max_length=32)
    author = models.CharField(max_length=32)
    animal = models.ForeignKey('Animal',on_delete=models.CASCADE)

class AnimalPic(models.Model):
    apicture = models.ImageField(upload_to='animal/images')
    animal = models.ForeignKey('Animal',on_delete=models.CASCADE)
    animalstore = models.ForeignKey('AnimalStore',on_delete=models.CASCADE)

animal/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'animal/animal_index.html')

def list(request):
    return render(request,'animal/animal_list.html')

def add(request):
    return render(request,'animal/animal_add.html')

templates/animal/animal_add.html
{% extends 'base.html' %}
{% block banner %}
    <div><a href=""><img style="height: 400px" src="/static/images/banner4.jpg" alt=""></a></div>
    <div><a href=""><img style="height: 400px" src="/static/images/banner4.jpg" alt=""></a></div>
    <div><a href=""><img style="height: 400px" src="/static/images/banner4.jpg" alt=""></a></div>
{% endblock %}
<!--移动端  Mmenu-->
{% block content %}


<nav id="mmenu">
    <ul>
        <li><a href="">English</a></li>
        <li><a href="index.html">首 页</a></li>
        <li><a href="brand.html">品牌简介</a>
            <ul>
                <li><a href="brand.html">品牌简介</a></li>
                <li><a href="">企业文化</a></li>
                <li><a href="animal_index.html">荣誉资质</a></li>
            </ul>
        </li>
        <li><a href="product.html">产品中心</a>
            <ul>
                <li><a href="">婚礼花艺</a>
                    <ul>
                        <li><a href="">求婚必备</a></li>
                        <li><a href="">情人节专属</a></li>
                        <li><a href="">其他鲜花</a></li>
                    </ul>
                </li>
                <li><a href="product.html">爱情鲜花</a>
                    <ul>
                        <li><a href="">求婚必备</a></li>
                        <li><a href="product.html">情人节专属</a></li>
                        <li><a href="">其他鲜花</a></li>
                    </ul>
                </li>
                <li><a href="">长辈鲜花</a>
                    <ul>
                        <li><a href="">求婚必备</a></li>
                        <li><a href="">情人节专属</a></li>
                        <li><a href="">其他鲜花</a></li>
                    </ul>
                </li>

            </ul>
        </li>
        <li><a href="case.html">经典案例</a>
            <ul>
                <li><a href="case.html">经典案例</a></li>
                <li><a href="">新增分类</a></li>
            </ul>
        </li>
        <li><a href="flower.html">花之物语</a>
            <ul>
                <li><a href="flower.html">花之物语</a></li>
                <li><a href="">养花知识</a></li>
            </ul>
        </li>
        <li><a href="contact.html">联系我们</a>
            <ul>
                <li><a href="contact.html">联系我们</a></li>
                <li><a href="message.html">在线留言</a></li>
                <li><a href="job.html">人才招聘</a></li>
            </ul>
        </li>
    </ul>
</nav>

</div>

<!--内页内容区域-->
<div class="container ny-wrap">
    <div class="pro-title clearfix">
        <span class="pull-left">联系我们</span>
        <p class="pull-right">
            <a href="contact.html">联系我们</a><em>|</em>
            <a class="active" href="message.html">在线留言</a><em>|</em>
            <a href="job.html">人才招聘</a>
        </p>
    </div>
    <div class="container message">
        <div class="messageh">
            <h2>There is doubt through the below <br/>message to consult us! </h2>
            <span>有疑问就通过下方留言来咨询我们吧！</span>
        </div>
        <div class="message-con clearfix">
            <div class="mcon-left pic pull-left"><img src="/static/images/haozi0.jpg" class="vcenter" alt=""/></div>
            <div class="mcon-right pull-right">
                <label><span>姓名</span><input type="text" class="mname" value=""/><em>*</em></label>
                <label><span>联系电话</span><input type="text" class="mtel"/><em>*</em></label>
                <label><span>联系地址</span><input type="text" class="madd"/></label>
                <label><span>邮箱地址</span><input type="text" class="memail"/></label>
                <label><span>留言内容</span><textarea name="" class="mcontent"></textarea><em>*</em></label>
                <label class="mcodela"><input type="text" class="mcode"/><img src="/static/images/mcode.jpg" alt=""/><a
                        href="#">看不清楚？换一张</a><em>*</em></label>
                <label><input type="submit" class="msub" value="在线提交"/></label>
            </div>
        </div>
    </div>


    <!--花之物语-->
    {% include 'animal/animals_include.html' %}
    {% endblock %}
</div>

templates/animal/animal_index.html
{% extends 'base.html' %}

{% block banner %}
    <div><a href=""><img style="height: 400px" src="/static/images/banner4.jpg" alt=""></a></div>
    <div><a href=""><img style="height: 400px" src="/static/images/banner4.jpg" alt=""></a></div>
    <div><a href=""><img style="height: 400px" src="/static/images/banner4.jpg" alt=""></a></div>

{% endblock %}
{% block content %}

<!--移动端  Mmenu-->
<nav id="mmenu">
    <ul>
        <li><a href="">English</a></li>
        <li><a href="index.html">首 页</a></li>
        <li><a href="brand.html">品牌简介</a>
            <ul>
                <li><a href="brand.html">品牌简介</a></li>
                <li><a href="">企业文化</a></li>
                <li><a href="animal_index.html">荣誉资质</a></li>
            </ul>
        </li>
        <li><a href="product.html">产品中心</a>
            <ul>
                <li><a href="">婚礼花艺</a>
                    <ul>
                        <li><a href="">求婚必备</a></li>
                        <li><a href="">情人节专属</a></li>
                        <li><a href="">其他鲜花</a></li>
                    </ul>
                </li>
                <li><a href="product.html">爱情鲜花</a>
                    <ul>
                        <li><a href="">求婚必备</a></li>
                        <li><a href="product.html">情人节专属</a></li>
                        <li><a href="">其他鲜花</a></li>
                    </ul>
                </li>
                <li><a href="">长辈鲜花</a>
                    <ul>
                        <li><a href="">求婚必备</a></li>
                        <li><a href="">情人节专属</a></li>
                        <li><a href="">其他鲜花</a></li>
                    </ul>
                </li>

            </ul>
        </li>
        <li><a href="case.html">经典案例</a>
            <ul>
                <li><a href="case.html">经典案例</a></li>
                <li><a href="">新增分类</a></li>
            </ul>
        </li>
        <li><a href="flower.html">花之物语</a>
            <ul>
                <li><a href="flower.html">花之物语</a></li>
                <li><a href="">养花知识</a></li>
            </ul>
        </li>
        <li><a href="contact.html">联系我们</a>
            <ul>
                <li><a href="contact.html">联系我们</a></li>
                <li><a href="message.html">在线留言</a></li>
                <li><a href="job.html">人才招聘</a></li>
            </ul>
        </li>
    </ul>
</nav>

</div>

<!--内页内容区域-->
<div class="container ny-wrap">
    <div class="pro-title clearfix">
        <span class="pull-left">萌宠来了</span>
        <p class="pull-right">
            <a href="brand.html">品牌简介</a><em>|</em>
            <a href="#">企业文化</a><em>|</em>
            <a class="active" href="{% url 'animal:a_index' %}">萌宠来了</a>
        </p>
    </div>
    <div class="container honor">
        <div class="container">
            <div class="about-visual-recommon">
                <div class="pics-1 wow bounceInDown" data-wow-delay=".2s" id="slick-1">
                    <div>
                        <a href="javascript:;" class="items block">
                            <i class="pic"><img src="/static/images/haozi0.jpg" class="vcenter" alt=""/></i>
                            <span class="name">仓鼠小可爱</span>
                        </a>
                    </div>
                    <div>
                        <a href="javascript:;" class="items block">
                            <i class="pic"><img src="/static/images/samoye.jpg" class="vcenter" alt=""/></i>
                            <span class="name">别跑肯定能追上你的</span>
                        </a>
                    </div>
                    <div>
                        <a href="javascript:;" class="items block">
                            <i class="pic"><img src="/static/images/rundog.jpg" class="vcenter" alt=""/></i>
                            <span class="name">短腿柯基满草坪跑来跑去</span>
                        </a>
                    </div>
                    <div>
                        <a href="javascript:;" class="items block">
                            <i class="pic"><img src="/static/images/cat9.jpg" class="vcenter" alt=""/></i>
                            <span class="name">你瞅,这多招人稀罕啊</span>
                        </a>
                    </div>
                    <div>
                        <a href="javascript:;" class="items block">
                            <i class="pic"><img src="/static/images/dog3.jpg" class="vcenter" alt=""/></i>
                            <span class="name">你看你笑起来是不是很像他</span>
                        </a>
                    </div>
                </div>

                <div class="pics2-2">
                    <div class="pics2-1">
                        <div class="pics-2 wow bounceInDown" id="slick-2" style="top:-25px;left:20px">
                            <div>
                                <a href="javascript:;" class="items block">
                                    <i class="pic"><img src="/static/images/samoye.jpg" class="vcenter" alt=""/></i>
                                    <span class="name"></span>
                                </a>
                            </div>
                            <div>
                                <a href="javascript:;" class="items block">
                                    <i class="pic"><img src="/static/images/rundog.jpg" class="vcenter" alt=""/></i>
                                    <span class="name">短腿柯基满草坪跑来跑去</span>
                                </a>
                            </div>
                            <div>
                                <a href="javascript:;" class="items block">
                                    <i class="pic"><img src="/static/images/cat9.jpg" class="vcenter" alt=""/></i>
                                    <span class="name">你瞅,这可太招人稀罕了</span>
                                </a>
                            </div>
                            <div>
                                <a href="javascript:;" class="items block">
                                    <i class="pic"><img src="/static/images/dog3.jpg" class="vcenter" alt=""/></i>
                                    <span class="name">你看你笑起来是不是很像他</span>
                                </a>
                            </div>
                            <div>
                                <a href="javascript:;" class="items block">
                                    <i class="pic"><img src="/static/images/haozi0.jpg" class="vcenter" alt=""/></i>
                                    <span class="name">仓鼠小可爱</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="controller">
                    <a href="javascript:;" class="wow bounceInDown" id="slick-1-prev" data-wow-delay=".3s"></a>
                    <a href="javascript:;" class="wow bounceInDown" id="slick-1-next" data-wow-delay=".4s"></a>
                </div>

            </div>
        </div>


    </div>

   {% include 'animal/animals_include.html' %}
{% endblock %}

{% block script %}
<!--placeholder-->
<script src="/static/js/jquery.placeholder.min.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
	$(function(){ $('input, textarea').placeholder(); });
</script>
<script type="text/javascript">
        $(document).ready(function() {
            $("#slick-1").slick({
                arrows: false,
                draggable: false,
                useTransform: true
            }).slick("slickGoTo", 1);
            $("#slick-2").slick({
                arrows: false,
                draggable: false,
                useTransform: true
            });

            /*Controller*/
            $("#slick-1-prev").click(function() {
                $("#slick-1,#slick-2").slick("slickPrev");
            })
            $("#slick-1-next").click(function() {
                $("#slick-1,#slick-2").slick("slickNext");
            })
            $("#slick-1-next,#slick-1-prev").click(function() {
                $(".about-visual-recommon").toggleClass("active");
            })
        })
    </script>
{% endblock %}

templates/animal/animal_list.html
{% extends 'base.html' %}
{% block banner %}
    <div><a href=""><img style="height: 400px" src="/static/images/banner4.jpg" alt=""></a></div>
    <div><a href=""><img style="height: 400px" src="/static/images/banner4.jpg" alt=""></a></div>
    <div><a href=""><img style="height: 400px" src="/static/images/banner4.jpg" alt=""></a></div>
{% endblock %}


{% block content %}


    <!--移动端  Mmenu-->
    <nav id="mmenu">
        <ul>
            <li><a href="">English</a></li>
            <li><a href="index.html">首 页</a></li>
            <li><a href="brand.html">品牌简介</a>
                <ul>
                    <li><a href="brand.html">品牌简介</a></li>
                    <li><a href="">企业文化</a></li>
                    <li><a href="animal_index.html">荣誉资质</a></li>
                </ul>
            </li>
            <li><a href="product.html">产品中心</a>
                <ul>
                    <li><a href="">婚礼花艺</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>
                    <li><a href="product.html">爱情鲜花</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="product.html">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>
                    <li><a href="">长辈鲜花</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>

                </ul>
            </li>
            <li><a href="case.html">经典案例</a>
                <ul>
                    <li><a href="case.html">经典案例</a></li>
                    <li><a href="">新增分类</a></li>
                </ul>
            </li>
            <li><a href="flower.html">花之物语</a>
                <ul>
                    <li><a href="flower.html">花之物语</a></li>
                    <li><a href="">养花知识</a></li>
                </ul>
            </li>
            <li><a href="contact.html">联系我们</a>
                <ul>
                    <li><a href="contact.html">联系我们</a></li>
                    <li><a href="message.html">在线留言</a></li>
                    <li><a href="job.html">人才招聘</a></li>
                </ul>
            </li>
        </ul>
    </nav>

  

    <!--内页内容区域-->
    <div class="container ny-wrap">
        <div class="pro-title clearfix">
            <span class="pull-left">花之物语</span>
            <p class="pull-right">
                <a class="active" href="{% url 'animal:a_add' %}">欢迎补充</a><em>|</em>
                <a href="#">养花知识</a>
            </p>
        </div>
        <div class="container flower-wuyu">
            <ul class="clearfix">
                <li>
                    <div class="pic"><a href="animal_show.html"><img src="/static/images/flower-img1.png" class="vcenter"
                                                                     alt=""/></a></div>
                    <div class="flowertxt">
                        <span>2016.06.14</span>
                        <a href="animal_show.html">花之物语信息测试某某科技有限公司所服务的陆金所荣获第七届虎啸奖年度广告主杰...</a>
                        <p>2016年6月6日，第十届虎啸国际高峰论坛暨第七届虎啸奖颁奖盛典在上海隆重举行。作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办七届。</p>
                        <a href="animal_show.html" class="flower-jt"></a>
                    </div>
                </li>
                <li>
                    <div class="pic"><a href="animal_show.html"><img src="/static/images/flower-img2.png" class="vcenter"
                                                                     alt=""/></a></div>
                    <div class="flowertxt">
                        <span>2016.06.14</span>
                        <a href="animal_show.html">花之物语信息测试某某科技有限公司总裁赵旭隆荣膺第七届虎啸奖年度人物大奖</a>
                        <p>
                            虎啸奖由虎啸传媒发起并创立，中国商务广告协会数字营销委员会与虎啸传媒联合主办。作为少数专注数字营销的高端盛会之一，本届大赛共收录近240家公司的作品1500余件，案例类共甄选出来120余家公司的420...</p>
                        <a href="animal_show.html" class="flower-jt"></a>
                    </div>
                </li>
                <li>
                    <div class="pic"><a href="animal_show.html"><img src="/static/images/flower-img3.png" class="vcenter"
                                                                     alt=""/></a></div>
                    <div class="flowertxt">
                        <span>2016.06.14</span>
                        <a href="animal_show.html">因为有你，一切珍好—— <br/>某某五月员工生日会</a>
                        <p>夏天的脚步悄悄靠近，而某某科技有限公司，也迎来了五月生日会，三月热情的BBQ，四月神奇的密室逃脱，还历历在目，五月又会带来怎样的惊喜，duang~duang~duang~</p>
                        <a href="animal_show.html" class="flower-jt"></a>
                    </div>
                </li>
                <li>
                    <div class="pic"><a href="animal_show.html"><img src="/static/images/flower-img4.png" class="vcenter"
                                                                     alt=""/></a></div>
                    <div class="flowertxt">
                        <span>2016.06.14</span>
                        <a href="animal_show.html">花之物语信息测试“鸿鹄之 · 智”2016新浪程序化营销峰会圆满落幕</a>
                        <p>
                            虎啸奖由虎啸传媒发起并创立，中国商务广告协会数字营销委员会与虎啸传媒联合主办。作为少数专注数字营销的高端盛会之一，本届大赛共收录近240家公司的作品1500余件，案例类共甄选出来120余家公司的420...</p>
                        <a href="animal_show.html" class="flower-jt"></a>
                    </div>
                </li>
                <li>
                    <div class="pic"><a href="animal_show.html"><img src="/static/images/flower-img5.png" class="vcenter"
                                                                     alt=""/></a></div>
                    <div class="flowertxt">
                        <span>2016.06.14</span>
                        <a href="animal_show.html">花之物语信息测试某某科技有限公司所服务的陆金所荣获第七届虎啸奖年度广告主杰...</a>
                        <p>2016年6月6日，第十届虎啸国际高峰论坛暨第七届虎啸奖颁奖盛典在上海隆重举行。作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办七届。</p>
                        <a href="animal_show.html" class="flower-jt"></a>
                    </div>
                </li>
                <li>
                    <div class="pic"><a href="animal_show.html"><img src="/static/images/flower-img6.png" class="vcenter"
                                                                     alt=""/></a></div>
                    <div class="flowertxt">
                        <span>2016.06.14</span>
                        <a href="animal_show.html">花之物语信息测试营销界“绝代双骄”如何双剑合璧？</a>
                        <p>
                            虎啸奖由虎啸传媒发起并创立，中国商务广告协会数字营销委员会与虎啸传媒联合主办。作为少数专注数字营销的高端盛会之一，本届大赛共收录近240家公司的作品1500余件，案例类共甄选出来120余家公司的420...</p>
                        <a href="animal_show.html" class="flower-jt"></a>
                    </div>
                </li>
            </ul>
            <div class="page">
                <a href="#">首页</a>
                <a class="prev" href="#"><img src="/static/images/pre-bg.png" alt=""/> 上一页</a>
                <a href="#">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
                <a href="#">5</a>
                <a href="#">6</a>
                <a class="next" href="#">下一页 <img src="/static/images/next-bg.png" alt=""/></a>
                <a href="#">尾页</a>
            </div>
        </div>
        <div class="container new-pro">
            <div class="case-title">
                <h3>新品推荐</h3>
                <span><img src="/static/images/pro-casebg.png" alt=""/>NEW PRODUCTS</span>
            </div>
            <div class="love-wrap">
                <ul class="clearfix">
                    <li>
                        <div class="pic"><a href="pro_show.html"><img src="/static/images/love1.jpg" class="vcenter"/></a></div>
                        <p><a href="pro_show.html">海洋之心</a><em>¥</em> <span>399</span></p>
                    </li>
                    <li>
                        <div class="pic"><a href="pro_show.html"><img src="/static/images/love2.jpg" class="vcenter"/></a></div>
                        <p><a href="pro_show.html">给柏拉图的信</a><em>¥</em> <span>399</span></p>
                    </li>
                    <li>
                        <div class="pic"><a href="pro_show.html"><img src="/static/images/love3.jpg" class="vcenter"/></a></div>
                        <p><a href="pro_show.html">雍容</a><em>¥</em> <span>399</span></p>
                    </li>
                    <li>
                        <div class="pic"><a href="pro_show.html"><img src="/static/images/love4.jpg" class="vcenter"/></a></div>
                        <p><a href="pro_show.html">普罗旺斯的一年</a><em>¥</em> <span>1999</span></p>
                    </li>
                </ul>
            </div>
        </div>

    </div>

{% endblock %}

templates/animal/animals_include.html
 <!--花之物语-->
    <div class="container flower-tips clearfix">
        <div class="flowerh pull-left">
            <h3>ANIMAL TIPS</h3>
            <div><span>萌宠宝贝</span><em></em></div>
            <a href="{% url 'animal:a_list' %}">查看更多</a>
            <p>宠物是我们的朋友,能给我们带来欢乐的同时,不要忘了,更多的了解他。</p>
        </div>
        <div class="flowertips-con pull-right">
            <div class="flower-con">
                <ul>
                    <li>
                        <div class="flower-ch">
                            <span>06-12</span><a href="animal_show.html">时尚广告片中的自然花艺某某鲜花测试文字</a>
                            <div class="line"></div>
                        </div>
                        <p>2016年6月6日，第十届虎啸国际高峰论坛暨第七届虎啸奖颁奖盛典在上海隆重举行。作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办... </p>
                        <a class="gengduo" href="{% url 'animal:a_list' %}">Read more</a>
                    </li>
                    <li>
                        <div class="flower-ch">
                            <span>06-12</span><a href="animal_show.html">鲜花测试文字母亲节之与妈妈的美丽“花约”</a>
                            <div class="line"></div>
                        </div>
                        <p>作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办七届。在本届颁奖盛典上，某某科技有限公司创始人·总裁赵旭隆先生荣膺“年度人物大奖” </p>
                        <a class="gengduo" href="animal_show.html">Read more</a>
                    </li>
                    <li class="last">
                        <div class="flower-ch">
                            <span>06-12</span><a href="animal_show.html">时尚广告片中的自然花艺某某鲜花测试文字</a>
                            <div class="line"></div>
                        </div>
                        <p>2016年6月6日，第十届虎啸国际高峰论坛暨第七届虎啸奖颁奖盛典在上海隆重举行。作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办... </p>
                        <a class="gengduo" href="animal_show.html">Read more</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div