daylife/urls.py
from django.urls import path,re_path
from daylife import views

app_name = 'daylife'
urlpatterns = [
    path('daylist/',views.daylist,name='daylist'),
    path('daydetail/',views.daydetail,name='daydetail'),
    path('dayregister/',views.register,name='dayregister'),
    path('username_ajax/',views.username_ajax),
    path('daylogin/',views.login,name='daylogin'),
    path('daylife_add/',views.daylife_add,name='daylife_add'),
    path('daylife_delete/',views.daylife_delete,name='daylife_delete'),
    path('daydetail_add/',views.daydetail_add,name='daydetail_add'),
    path('daylife_echart',views.echart,name='dayechart')
]

enjoy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flower.urls')),
    path('animal/', include('animal.urls')),
    path('daylife/', include('daylife.urls'))
]

flower/urls.py
from django.urls import path
from flower import views

app_name = 'flower'
urlpatterns = [
    path('',views.index),
    path('flower_detail/',views.flower_detail,name='f_detail'),
    path('flower_list/',views.flower_list,name='f_list'),
    path('flower_add/',views.flower_add,name='f_add'),
    path('list_ajax/',views.list_ajax)
]

daylife/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=32)
    email = models.EmailField(max_length=32)
    password = models.CharField(max_length=32)

class Daylife(models.Model):
    title = models.CharField(max_length=32)
    date = models.CharField(max_length=32)
    detail = models.CharField(max_length=32)
    logo = models.ImageField(upload_to='daylife/images')

class Daystory(models.Model):
    story = models.CharField(max_length=32)
    pic = models.ImageField(upload_to='daylife/images')
    daylife = models.ForeignKey(to='Daylife',on_delete=models.CASCADE)

daylife/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import User


class UserForm(forms.Form):
    username = forms.CharField(max_length=32)
    email = forms.EmailField()
    pwd1 = forms.CharField(min_length=5)
    pwd2 = forms.CharField(min_length=5)

    def clean_name(self):
        name = self.cleaned_data.get('username')
        user = User.objects.filter(username=name)
        if user:
            raise ValidationError('用户名已存在不可注册')
        else:
            return name

daylife/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect,JsonResponse

from .forms import *
from .models import *

# Create your views here.

def register(request):
    if request.method=='POST':
        data_vaild = UserForm(request.POST)
        if data_vaild.is_valid():
            data = data_vaild.cleaned_data
            email = data.get("email")
            username = data.get("username")
            pwd = data.get("pwd2")
            user = User()
            user.username = username
            user.email = email
            user.password = pwd
            user.save()
            return HttpResponseRedirect('/daylife/daylogin/')
    return render(request,'daylife/register.html')


def username_ajax(request):
    result = {'code':400,'data':''}
    name = request.GET.get('name')
    user = User.objects.filter(username=name).first()
    if user:
        result['data'] ='用户名称已存在'
    else:
        result['data'] = ''
    return JsonResponse(result)


def login(request):
    if request.method =="POST":
        email = request.POST.get("email")
        pwd = request.POST.get('pwd1')
        user = User.objects.filter(email=email).first()
        if user:
            name = user.username
            id = user.id
            if user.password == pwd:
                response = HttpResponseRedirect('daylife:daylist')
                response.set_cookie('name',name)
                response.set_cookie('id',id)
                request.session['id']=id
                return response
    return render(request,'daylife/login.html')

def daydetail(request):
    # 列表页传来的日常id
    id = request.GET.get('id')
    if id:
        # 取日常故事对象显示到详情页
        life = Daylife.objects.filter(id=int(id)).first()
        # 取日常对应的详情故事
        story = life.daystory_set.all().last()
        # 查相关案例的推荐
        d_list = Daylife.objects.all()
    return render(request, 'daylife/day_detail.html',locals())

def daylist(request):
    d_list = Daylife.objects.all()
    return render(request,'daylife/daylist.html',locals())

# 对日常进行添加
def daylife_add(request):

    if request.method =='POST':
        title = request.POST.get('title')
        date = request.POST.get('date')
        detail = request.POST.get('introduce')
        picture = request.FILES.get('picture')
        d = Daylife()
        d.title = title
        d.date = date
        d.detail = detail
        d.logo = picture
        d.save()
        return redirect('daylife:daylist')
    return render(request,'daylife/daylife_add.html')

# 日常删除细节也跟着删除
def daylife_delete(request):
    id = request.GET.get('id') #这个id是点细节传过去的id
    Daylife.objects.get(id=int(id)).delete()
    return redirect('daylife:daylist')

# 对故事的详情进行添加
def daydetail_add(request):
    id = request.GET.get('id') #当前想要查找的详情id
    life = Daylife.objects.filter(id=int(id)).first()
    obj = life.daystory_set.all().first()
    dstory = obj.story
    # 是否有对应故事详情
    story_list = Daylife.objects.all()
    if request.method =='POST':
        pid = request.POST.get('pid') #外键id
        title = request.POST.get('title')
        story = Daylife.objects.get(id=int(pid))
        picture = request.FILES.get('picture')
        if not obj:
            obj = Daystory()
        obj.story = title
        obj.daylife=story
        obj.pic=picture
        obj.save()
        return redirect('/daylife/daydetail/?id='+id)
    return render(request,'daylife/daydetail_add.html',locals())

def echart(request):
    return render(request,'daylife/echart.html')

templates/daylife/day_detail.html
{% extends 'base.html' %}
{% load OurTag %}
	<!--banner-->
	<section class="banner nybanner">
       {% block banner %}
            <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
            <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
            <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
        {% endblock %}

    </section>
	


{% block content %}


<!--内页内容区域-->
<div class="container ny-wrap">
	<div class="pro-title clearfix">
		<span class="pull-left">分享日常</span>
		<p class="pull-right">
			<a class="active" href="case.html"></a><em>|</em>
			<a href="{% url 'daylife:daydetail_add' %}?id={{ id }}">继续分享</a>
{#            这是详情id#}
		</p>
	</div>
	<div class="container caseshow">
		<div class="fshow-title">
			<h1>{{ life.title }}</h1>
			<div class="date">
				<span>发布时间：{{life.date }}</span> &nbsp;&nbsp;<a style="font-size: 10px" href="{% url 'daylife:daylife_delete' %}?id={{ id }}">删除</a>
			</div>
		</div>
		<div class="fshow-con">
	<div class="fshowimg clearfix">
        <p> {{ story.story }}</p>
				<div class="pic"><img src="/static/{{ story.pic }}" class="vcenter" alt="" /></div>
			</div>
		</div>
		<!--上下篇-->
		<div class="container up-down">
			<a href="#"><b>上一篇：</b>无</a>
			<a href="#"><b>下一篇：</b>因为有你，一切珍好—— 某某五月员工生日会</a>
		</div>
	</div>
	
	
	<!--相关案例-->
	<div class="container case-wrap sycase xgcase xgcp">
		<div class="xgcp-title">
			<h3>还有一些日常</h3>
			<p>We hope that through the flower box of love, affection and friendship express intuitive, needless to say, everything is in the middle of the flower box. </p>
		</div>
		<div class="sycase-wrap case-con xgcase-con">
			<ul class="clearfix">
                {% for d in d_list|limit_2 %}
                    <li class="last">
					    <div class="pic"><a href="{% url 'daylife:daydetail' %}?id={{ d.id }}"><img src="/static/{{ d.logo }}" class="vcenter"  alt="" /></a></div>
					    <a href="{% url 'daylife:daydetail' %}?id={{ d.id }}" class="case-zzch">
					    	{{ d.title }}
					    </a>
					    <a href="{% url 'daylife:daydetail' %}?id={{ d.id }}" class="case-zzc">
					    	<h3>{{ d.date }}</h3>
					    	<p>{{ d.detail }}</p>
					    </a>
				    </li>
                {% endfor %}
			</ul>
		</div>
	</div>
	
	
</div>


{% endblock %}

templates/daylife/daydetail_add.html
{% extends 'base.html' %}

{% block banner %}
    <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
    <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
    <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
{% endblock %}
{% block content %}

    <!--移动端  Mmenu-->
    <nav id="mmenu">
        <ul>
            <li><a href="">English</a></li>
            <li><a href="index.html">首 页</a></li>
            <li><a href="brand.html">品牌简介</a>
                <ul>
                    <li><a href="brand.html">品牌简介</a></li>
                    <li><a href="">企业文化</a></li>
                    <li><a href="honor.html">荣誉资质</a></li>
                </ul>
            </li>
            <li><a href="product.html">产品中心</a>
                <ul>
                    <li><a href="">婚礼花艺</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>
                    <li><a href="product.html">爱情鲜花</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="product.html">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>
                    <li><a href="">长辈鲜花</a>
                        <ul>
                            <li><a href="">求婚必备</a></li>
                            <li><a href="">情人节专属</a></li>
                            <li><a href="">其他鲜花</a></li>
                        </ul>
                    </li>

                </ul>
            </li>
            <li><a href="case.html">经典案例</a>
                <ul>
                    <li><a href="case.html">经典案例</a></li>
                    <li><a href="">新增分类</a></li>
                </ul>
            </li>
            <li><a href="flower.html">花之物语</a>
                <ul>
                    <li><a href="flower.html">花之物语</a></li>
                    <li><a href="">养花知识</a></li>
                </ul>
            </li>
            <li><a href="contact.html">联系我们</a>
                <ul>
                    <li><a href="contact.html">联系我们</a></li>
                    <li><a href="message.html">在线留言</a></li>
                    <li><a href="job.html">人才招聘</a></li>
                </ul>
            </li>
        </ul>
    </nav>

    </div>

    <!--内页内容区域-->
    <div class="container ny-wrap">
        <div class="pro-title clearfix">
            <span class="pull-left">信息详情</span>
            <p class="pull-right">
                {#			<a href="contact.html">联系我们</a><em>|</em>#}
                {#			<a class="active" href="message.html">在线留言</a><em>|</em>#}
                {#			<a href="job.html">人才招聘</a>#}
            </p>
        </div>
        <div class="container message">
            <div class="messageh">
                <h2>There is doubt through the below <br/>message to consult us! </h2>
                <span></span>
            </div>
            <div class="message-con clearfix">
                <div class="mcon-left pic pull-left"><img src="/static/images/bg1.jpg" class="vcenter" alt=""/>
                </div>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                     <div class="mcon-right pull-right">
                        <label><span>date</span><select name="pid" id="">
                            {% for story in story_list%}
                                <option value="{{ story.id }}">{{ story.date }}</option>
                            {% endfor %}
                        </select></label>
                         <br>
                         <label><span>what's the detail</span><textarea  name="title" id="title" placeholder="说说今天都发生了什么吧----{{ dstory }}" ></textarea></label>
                         <br>
                        <label><span>pictures</span><input type="file" name="picture" id="picture" multiple='multiple' ></label>
                         <br>
                        <label><input type="submit" class="msub" value="提交"/></label>
                    </div>

                </form>
            </div>
        </div>


        <!--花之物语-->
        <div class="container flower-tips clearfix">
            <div class="flowerh pull-left">
                <h3>FLOWER TIPS</h3>
                <div><span>花之物语</span><em></em></div>
                <a href="flower.html">查看更多</a>
                <p>我们希望，通过花盒把爱情，亲情以及友情直观的表达出来，无需多言，一切尽在花盒当中。</p>
            </div>
            <div class="flowertips-con pull-right">
                <div class="flower-con">
                    <ul>
                        <li>
                            <div class="flower-ch">
                                <span>06-12</span><a href="flower_show.html">时尚广告片中的自然花艺某某鲜花测试文字</a>
                                <div class="line"></div>
                            </div>
                            <p>2016年6月6日，第十届虎啸国际高峰论坛暨第七届虎啸奖颁奖盛典在上海隆重举行。作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办... </p>
                            <a class="gengduo" href="flower_show.html">Read more</a>
                        </li>
                        <li>
                            <div class="flower-ch">
                                <span>06-12</span><a href="flower_show.html">鲜花测试文字母亲节之与妈妈的美丽“花约”</a>
                                <div class="line"></div>
                            </div>
                            <p>作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办七届。在本届颁奖盛典上，某某科技有限公司创始人·总裁赵旭隆先生荣膺“年度人物大奖” </p>
                            <a class="gengduo" href="flower_show.html">Read more</a>
                        </li>
                        <li class="last">
                            <div class="flower-ch">
                                <span>06-12</span><a href="flower_show.html">时尚广告片中的自然花艺某某鲜花测试文字</a>
                                <div class="line"></div>
                            </div>
                            <p>2016年6月6日，第十届虎啸国际高峰论坛暨第七届虎啸奖颁奖盛典在上海隆重举行。作为商业传播领域最具权威性、前瞻性及创新性的大型赛事活动之一，虎啸奖至今已成功举办... </p>
                            <a class="gengduo" href="flower_show.html">Read more</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/daylife/daylist.html
{% extends 'base.html' %}
			
	<!--banner-->
	<section class="banner nybanner">
        {% block banner %}
            <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
            <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
            <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
        {% endblock %}
    </section>

{% block content %}
<!--内页内容区域-->
<div class="container ny-wrap">
	<div class="pro-title clearfix">
		<span class="pull-left">日常分享</span>
		<p class="pull-right">
			<a class="active" href="case.html"></a><em>|</em>
			<a href="{% url 'daylife:daylife_add' %}">新增日常</a>
		</p>
	</div>
	<div class="container case-wrap sycase case">
		<div class="sycase-wrap case-con clearfix">
			<ul class="clearfix">
                {% for d in d_list %}
                    <li class="last">
					    <div class="pic"><a href="{% url 'daylife:daydetail' %}?id={{ d.id }}"><img src="/static/{{ d.logo }}" class="vcenter"  alt="" /></a></div>
					    <a href="{% url 'daylife:daydetail' %}?id={{ d.id }}" class="case-zzch">
					    	{{ d.title }}
					    </a>
					    <a href="{% url 'daylife:daydetail' %}?id={{ d.id }}" class="case-zzc">
					    	<h3>{{ d.date }}</h3>
					    	<p>{{ d.detail }}</p>
					    </a>
				    </li>
                {% endfor %}

			</ul>
			<div class="page">
				<a href="#">首页</a>
				<a class="prev" href="#"><img src="/static/images/pre-bg.png" alt="" /> 上一页</a>
				<a href="#">1</a>
				<a href="#">2</a>
				<a href="#">3</a>
				<a href="#">4</a>
				<a href="#">5</a>
				<a href="#">6</a>
				<a class="next" href="#">下一页 <img src="/static/images/next-bg.png" alt="" /></a>
				<a href="#">尾页</a>
			</div>
		</div>
	</div>
	
	
	

	
	
</div>

{% endblock %}

templates/daylife/echart.html
{% extends 'base.html' %}
{% block banner %}
    <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
    <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
    <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>

{% endblock %}
{% block content %}
    <div style="height: 500px;width: 1380px;background: url('/static/images/back1.jpg') no-repeat">
    <div style="margin-left:400px; width: 600px;height: 500px" id="panel"></div>
    </div>
{% endblock %}
{% block script %}
    <script src="/static/js/echarts.min.js"></script>
    <script>
        var myChart = echarts.init(document.getElementById('panel'));
        var colors = ['#1ca9f3', '#d134a0', '#1b00ba'];
        option = {
            color: colors,

            tooltip: {
                trigger: 'none',
                axisPointer: {
                    type: 'cross'
                }
            },
            legend: {
                data:['出门时间', '学习时间']
            },
            grid: {
                top: 70,
                bottom: 50
            },
            xAxis: [
                {
                    type: 'category',
                    axisTick: {
                        alignWithLabel: true
                    },
                    axisLine: {
                        onZero: false,
                        lineStyle: {
                            color: colors[1]
                        }
                    },
                    axisPointer: {
                        label: {
                            formatter: function (params) {
                                return '学习时间  ' + params.value
                                    + (params.seriesData.length ? '：' + params.seriesData[0].data : '');
                            }
                        }
                    },
                    data: ['1/19', '1/20', '1/21', '1/22', '1/23', '1/24', '1/25', '1/26', '1/27']
                },
                {
                    type: 'category',
                    axisTick: {
                        alignWithLabel: true
                    },
                    axisLine: {
                        onZero: false,
                        lineStyle: {
                            color: colors[0]
                        }
                    },
                    axisPointer: {
                        label: {
                            formatter: function (params) {
                                return '出门时间  ' + params.value
                                    + (params.seriesData.length ? '：' + params.seriesData[0].data : '');
                            }
                        }
                    },
                    data: ['1/19', '1/20', '1/21', '1/22', '1/23', '1/24', '1/25', '1/26', '1/27']
                }
            ],
            yAxis: [
                {
                    type: 'value'
                }
            ],
            series: [
                {
                    name: '出门时间',
                    type: 'line',
                    xAxisIndex: 1,
                    smooth: true,
                    data: [6,0,3,8,2,0,0,0,0]
                },
                {
                    name: '学习时间',
                    type: 'line',
                    smooth: true,
                    data: [0,4,4,0,5,0,2,6,0]
                }
            ]
        };
        myChart.setOption(option);

    </script>
{% endblock %}

templates/daylife/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>{% block title %}
        小王同学
    {% endblock %}</title>
    <meta name="keywords" content="某某科技有限公司">
    <meta name="description" content="某某科技有限公司">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="/static/images/favicon.ico">

    <!-- include main css -->
    <link rel="stylesheet" type="text/css" href="/static/css/slick.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.mmenu.all.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.mCustomScrollbar.css"/>
    <link rel="stylesheet" href="http://cdn.bootcss.com/animate.css/3.5.1/animate.min.css">
    {% block style %}

    {% endblock %}
    <!--[if lt IE 9]>
    <script src="http://apps.bdimg.com/libs/html5shiv/r29/html5.min.js"></script>
    <script src="http://apps.bdimg.com/libs/respond.js/1.4.2/respond.min.js"></script>

    <![endif]-->


</head>
<body>

<div>

    <!--header-->
    <header class="header">
        <section class="container naver clearfix">
            <div class="logo pull-left"><a href="flower/index.html" title="某某科技有限公司" alt="某某科技有限公司">MOU MOU</a></div>
            <nav class="nav pull-left">
                <ul>
                    <li class="active"><a href="/">首页</a></li>
                    <li><a href="brand.html">个人爱好</a>
                        <ul>
                            <li><a href="brand.html">品牌简介</a></li>
                            <li><a href="#">企业文化</a></li>
                            <li><a href="honor.html">荣誉资质</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'flower:f_list' %}">花之物语</a>
                        <ul>
                            <li><a href="product.html">婚礼花艺</a></li>
                            <li><a href="product.html">爱情鲜花</a></li>
                            <li><a href="product.html">长辈鲜花</a></li>
                        </ul>
                    </li>
                    <li><a href="case.html">萌宠宝贝</a>
                        <ul>
                            <li><a href="case.html">经典案例</a></li>
                            <li><a href="#">新增分类</a></li>
                        </ul>
                    </li>
                    <li><a href="flower.html">生活点滴</a>
                        <ul>
                            <li><a href="flower.html">花之物语</a></li>
                            <li><a href="#">养花知识</a></li>
                        </ul>
                    </li>
                    <li><a href="contact.html">故事分享</a>
                        <ul>
                            <li><a href="contact.html">联系我们</a></li>
                            <li><a href="message.html">在线留言</a></li>
                            <li><a href="job.html">人才招聘</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <div class="search pull-left">
                <img src="/static/images/search.png"/>
                <input type="text" class="top_search" value=""/>
                <input type="submit" class="top_sub" value="搜索"/>
            </div>
            <div class="language pull-right clearfix">
                <div class="language_wrap">
                    <a href="#">EN</a>
                    <a href="#">CN</a>
                </div>
                {#                <span>18145612345</span>#}
            </div>
        </section>
        <section class="container">
            <a href="#mmenu" class="phone-nav glyphicon glyphicon-list"></a>
        </section>

        <!--banner-->
        <section class="banner nybanner">
            {% block banner %}
                <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
                <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
                <div><a href=""><img style="height: 400px" src="/static/images/banner12.jpg" alt=""></a></div>
            {% endblock %}

        </section>
    </header>
    {% block content %}
        <div style="margin: 100px 100px">
     <form class="form-horizontal" role="form" method="post">
         {% csrf_token %}
            <div class="form-group">
            <label for="email" class="col-sm-5 control-label">邮箱</label>
            <div class="col-sm-5">
                <input type="email" class="form-control" name="email" placeholder="请输入邮箱">
            </div>
            </div>
            <div class="form-group">
            <label for="email" class="col-sm-5 control-label">密码</label>
            <div class="col-sm-5">
                <input type="password" class="form-control" id="pwd1" name="pwd1" placeholder="请输入密码">
            </div>
            </div>
            <div class="form-group">
            <label for="email" class="col-sm-5 control-label"></label>
            <div class="col-sm-2">
                <input type="submit" class="form-control" value="提交">
            </div>
            </div>
         </form>
    </div>
    {% endblock %}
    <!--底部导航-->
    <div class="container footer-nav">
        <div class="panel-footer clearfix">
            <div class="footer-left pull-left">
                <ul>
                    <li><a href="/">首页</a></li>
                    <li><a href="brand.html">个人爱好</a></li>
                    <li><a href="{% url 'flower:f_list' %}">花之物语</a></li>
                    <li><a href="case.html">萌宠宝贝</a></li>
                    <li><a href="flower.html">生活点滴</a></li>
                    <li><a href="contact.html">故事分享</a></li>
                    <li><a href="map.html">站点地图</a></li>
                </ul>
            </div>
            <div class="footer-right pull-right">
                <div class="friend">
                    <a href="https://www.baidu.com/">友情链接</a>
                    <img class="pull-right" src="/static/images/friends-bg.png" alt=""/>
                </div>
                <div class="dropdown">
                    <a href="http://www.baidu.com" target="_blank">百度一下，你就知道</a>
                </div>
            </div>
        </div>

    </div>
</div>
<script src="http://apps.bdimg.com/libs/jquery/1.8.3/jquery.min.js" type="text/javascript" charset="utf-8"></script>

<!--移动端导航-->
<script src="/static/js/jquery.mmenu.all.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/vue/vue.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/vue/vue-resource.js" type="text/javascript" charset="utf-8"></script>

<script src="/static/js/public.js" type="text/javascript" charset="utf-8"></script>
<script src="http://cdn.bootcss.com/wow/1.1.2/wow.min.js"></script>
<script>
    if (getIEVersion() !== "IE8") {
        new WOW().init();
    }
    ;
</script>
<!--slick-->
<script src="/static/js/slick.min.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
    $(function () {
        $('.banner').slick({
            dots: false,
            autoplay: true,
            arrows: true,
            autoplaySpeed: 3000,
        });
    });
</script>

<!--placeholder-->
<script src="/static/js/jquery.placeholder.min.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
    $(function () {
        $('input, textarea').placeholder();
    });
</script>
{% block script %}

{% endblock %}

<!--<script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->


</body>
</html>