animal/urls.py
from django.urls import path,re_path
from animal import views

app_name = 'animal'
urlpatterns = [
    path('index/',views.index,name='a_index'),
    path('list/',views.list,name = 'a_list'),
    path('add/',views.add,name = 'a_add'),

]

daylife/urls.py
from django.urls import path,re_path
from daylife import views

app_name = 'daylife'
urlpatterns = [
    path('daylist/',views.daylist,name='daylist'),
    path('daydetail/',views.daydetail,name='daydetail'),
    path('dayregister/',views.register,name='dayregister'),
    path('username_ajax/',views.username_ajax),
    path('daylogin/',views.login,name='daylogin'),
    path('daylife_add/',views.daylife_add,name='daylife_add'),
    path('daylife_delete/',views.daylife_delete,name='daylife_delete'),
    path('daydetail_add/',views.daydetail_add,name='daydetail_add'),
    path('daylife_echart',views.echart,name='dayechart')
]

enjoy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flower.urls')),
    path('animal/', include('animal.urls')),
    path('daylife/', include('daylife.urls'))
]

flower/urls.py
from django.urls import path
from flower import views

app_name = 'flower'
urlpatterns = [
    path('',views.index),
    path('flower_detail/',views.flower_detail,name='f_detail'),
    path('flower_list/',views.flower_list,name='f_list'),
    path('flower_add/',views.flower_add,name='f_add'),
    path('list_ajax/',views.list_ajax)
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>{% block title %}
        小王同学
    {% endblock %}</title>
    <meta name="keywords" content="某某科技有限公司">
    <meta name="description" content="某某科技有限公司">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="/static/images/favicon.ico">

    <!-- include main css -->
    <link rel="stylesheet" type="text/css" href="/static/css/slick.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.mmenu.all.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.mCustomScrollbar.css"/>
    <link rel="stylesheet" href="http://cdn.bootcss.com/animate.css/3.5.1/animate.min.css">
    {% block style %}

    {% endblock %}
    <!--[if lt IE 9]>
    <script src="http://apps.bdimg.com/libs/html5shiv/r29/html5.min.js"></script>
    <script src="http://apps.bdimg.com/libs/respond.js/1.4.2/respond.min.js"></script>

    <![endif]-->


</head>
<body>

<div>

    <!--header-->
    <header class="header">
        <section class="container naver clearfix">
            <div class="logo pull-left"><a href="flower/index.html" title="某某科技有限公司" alt="某某科技有限公司">MOU MOU</a></div>
            <nav class="nav pull-left">
                <ul>
                    <li class="active"><a href="/">首页</a></li>
                    <li><a href="brand.html">个人爱好</a>
                        <ul>
                            <li><a href="brand.html">品牌简介</a></li>
                            <li><a href="#">企业文化</a></li>
                            <li><a href="honor.html">荣誉资质</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'flower:f_list' %}">花之物语</a>
                        <ul>
                            <li><a href="product.html">婚礼花艺</a></li>
                            <li><a href="product.html">爱情鲜花</a></li>
                            <li><a href="product.html">长辈鲜花</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'animal:a_index' %}">萌宠宝贝</a>
                        <ul>
                            <li><a href="{% url 'daylife:daylist' %}">经典案例</a></li>
                            <li><a href="#">新增分类</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'daylife:daylist' %}">生活点滴</a>
                        <ul>
                            <li><a href="{% url 'daylife:dayechart' %}">日程分析</a></li>
                            <li><a href="#">养花知识</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'daylife:daylist' %}">故事分享</a>
                        <ul>
                            <li><a href="{% url 'daylife:dayechart' %}">联系我们</a></li>
                            <li><a href="message.html">在线留言</a></li>
                            <li><a href="job.html">人才招聘</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <div class="search pull-left">
                <img src="/static/images/search.png"/>
                <input type="text" class="top_search" value=""/>
                <input type="submit" class="top_sub" value="搜索"/>
            </div>
            <div class="language pull-right clearfix">
                <div class="language_wrap">
                    <a href="#">EN</a>
                    <a href="#">CN</a>
                </div>
                {#                <span>18145612345</span>#}
            </div>
        </section>
        <section class="container">
            <a href="#mmenu" class="phone-nav glyphicon glyphicon-list"></a>
        </section>

        <!--banner-->
        <section class="banner nybanner">
            {% block banner %}
                <div><a href=""><img style="height: 400px" src="/static/images/banner1.jpg" alt=""></a></div>
                <div><a href=""><img style="height: 400px" src="/static/images/banner1.jpg" alt=""></a></div>
                <div><a href=""><img style="height: 400px" src="/static/images/banner1.jpg" alt=""></a></div>
            {% endblock %}

        </section>
    </header>

    {% block content %}

    {% endblock %}
    <!--底部导航-->
    <div class="container footer-nav">
        <div class="panel-footer clearfix">
            <div class="footer-left pull-left">
                <ul>
                    <li><a href="/">首页</a></li>
                    <li><a href="brand.html">个人爱好</a></li>
                    <li><a href="{% url 'flower:f_list' %}">花之物语</a></li>
                    <li><a href="case.html">萌宠宝贝</a></li>
                    <li><a href="flower.html">生活点滴</a></li>
                    <li><a href="{% url 'daylife:daylist' %}">故事分享</a></li>
                    <li><a href="{% url 'daylife:dayechart' %}">日程分析</a></li>
                </ul>
            </div>
            <div class="footer-right pull-right">
                <div class="friend">
                    <a href="https://www.baidu.com/">友情链接</a>
                    <img class="pull-right" src="/static/images/friends-bg.png" alt=""/>
                </div>
                <div class="dropdown">
                    <a href="http://www.baidu.com" target="_blank">百度一下，你就知道</a>
                </div>
            </div>
        </div>

    </div>
</div>
<script src="http://apps.bdimg.com/libs/jquery/1.8.3/jquery.min.js" type="text/javascript" charset="utf-8"></script>

<!--移动端导航-->
<script src="/static/js/jquery-1.12.4.min.js"></script>
<script src="/static/js/jquery.mmenu.all.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/vue/vue.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/vue/vue-resource.js" type="text/javascript" charset="utf-8"></script>

<script src="/static/js/public.js" type="text/javascript" charset="utf-8"></script>
<script src="http://cdn.bootcss.com/wow/1.1.2/wow.min.js"></script>
<script>
    if (getIEVersion() !== "IE8") {
        new WOW().init();
    }
    ;
</script>
<!--slick-->
<script src="/static/js/slick.min.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
    $(function () {
        $('.banner').slick({
            dots: false,
            autoplay: true,
            arrows: true,
            autoplaySpeed: 3000,
        });
    });
</script>

<!--placeholder-->
<script src="/static/js/jquery.placeholder.min.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
    $(function () {
        $('input, textarea').placeholder();
    });
</script>
{% block script %}

{% endblock %}

<!--<script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->


</body>
</html>